#!/usr/bin/env bash

## VARIABLES
THIS_DIR=$(cd "$(dirname "$0")"; pwd)
TDCLI='https://valtman.name/files/telegram-cli-1222'

## Print Colorful
# Print text in red
prtred() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Print text in green
prtgrn() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}

cd ../tabchi/
name=bot
if [[ -e $name.lua ]] ; then
  i=1
  while [[ -e $name-$i.lua ]] ; do
      let i++
  done
  name=$name-$i
fi
cat bot.lua >> "$name".lua
sed -i 's/BOT-ID/'$i'/g' "$name".lua

cmd='./telegram-cli -p robot-'$i' -s bot-'$i'.lua'



expect_commands='
set timeout 200
spawn '$cmd'
expect "phone:"
send "'$1'\r"
expect "code:"
set code [exec php ../botsaz/bot.php '$i']
send "$code\r"
expect "Ready] 0>"
send \x03
send \x03
interact'
expect -c "${expect_commands//
/;}"
